package com.p1.dao;

import com.p1.pojo.DownloadHistory;
import com.p1.pojo.DownloadHistoryAndSong;
import com.p1.pojo.DownloadHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DownloadHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    long countByExample(DownloadHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int deleteByExample(DownloadHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer downloadHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int insert(DownloadHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int insertSelective(DownloadHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    List<DownloadHistory> selectByExample(DownloadHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    DownloadHistory selectByPrimaryKey(Integer downloadHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") DownloadHistory row, @Param("example") DownloadHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int updateByExample(@Param("row") DownloadHistory row, @Param("example") DownloadHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(DownloadHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int updateByPrimaryKey(DownloadHistory row);


    /**
     *  通过userId联表查询Song和DownloadHistory的数据
     */
    List<DownloadHistoryAndSong> selectDownloadHistoryAndSongByRid(int userId);
}