package com.p1.dao;

import com.p1.pojo.SearchHistory;
import com.p1.pojo.SearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    long countByExample(SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int deleteByExample(SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer searchHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int insert(SearchHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int insertSelective(SearchHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    List<SearchHistory> selectByExample(SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    SearchHistory selectByPrimaryKey(Integer searchHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") SearchHistory row, @Param("example") SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int updateByExample(@Param("row") SearchHistory row, @Param("example") SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(SearchHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    int updateByPrimaryKey(SearchHistory row);
}