package com.p1.pojo;

import java.util.ArrayList;
import java.util.List;

public class DownloadHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public DownloadHistoryExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDownloadHistoryIdIsNull() {
            addCriterion("download_history_id is null");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdIsNotNull() {
            addCriterion("download_history_id is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdEqualTo(Integer value) {
            addCriterion("download_history_id =", value, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdNotEqualTo(Integer value) {
            addCriterion("download_history_id <>", value, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdGreaterThan(Integer value) {
            addCriterion("download_history_id >", value, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("download_history_id >=", value, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdLessThan(Integer value) {
            addCriterion("download_history_id <", value, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("download_history_id <=", value, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdIn(List<Integer> values) {
            addCriterion("download_history_id in", values, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdNotIn(List<Integer> values) {
            addCriterion("download_history_id not in", values, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdBetween(Integer value1, Integer value2) {
            addCriterion("download_history_id between", value1, value2, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andDownloadHistoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("download_history_id not between", value1, value2, "downloadHistoryId");
            return (Criteria) this;
        }

        public Criteria andRidIsNull() {
            addCriterion("rid is null");
            return (Criteria) this;
        }

        public Criteria andRidIsNotNull() {
            addCriterion("rid is not null");
            return (Criteria) this;
        }

        public Criteria andRidEqualTo(Integer value) {
            addCriterion("rid =", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotEqualTo(Integer value) {
            addCriterion("rid <>", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThan(Integer value) {
            addCriterion("rid >", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThanOrEqualTo(Integer value) {
            addCriterion("rid >=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThan(Integer value) {
            addCriterion("rid <", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThanOrEqualTo(Integer value) {
            addCriterion("rid <=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidIn(List<Integer> values) {
            addCriterion("rid in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotIn(List<Integer> values) {
            addCriterion("rid not in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidBetween(Integer value1, Integer value2) {
            addCriterion("rid between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotBetween(Integer value1, Integer value2) {
            addCriterion("rid not between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFavIsNull() {
            addCriterion("fav is null");
            return (Criteria) this;
        }

        public Criteria andFavIsNotNull() {
            addCriterion("fav is not null");
            return (Criteria) this;
        }

        public Criteria andFavEqualTo(Integer value) {
            addCriterion("fav =", value, "fav");
            return (Criteria) this;
        }

        public Criteria andFavNotEqualTo(Integer value) {
            addCriterion("fav <>", value, "fav");
            return (Criteria) this;
        }

        public Criteria andFavGreaterThan(Integer value) {
            addCriterion("fav >", value, "fav");
            return (Criteria) this;
        }

        public Criteria andFavGreaterThanOrEqualTo(Integer value) {
            addCriterion("fav >=", value, "fav");
            return (Criteria) this;
        }

        public Criteria andFavLessThan(Integer value) {
            addCriterion("fav <", value, "fav");
            return (Criteria) this;
        }

        public Criteria andFavLessThanOrEqualTo(Integer value) {
            addCriterion("fav <=", value, "fav");
            return (Criteria) this;
        }

        public Criteria andFavIn(List<Integer> values) {
            addCriterion("fav in", values, "fav");
            return (Criteria) this;
        }

        public Criteria andFavNotIn(List<Integer> values) {
            addCriterion("fav not in", values, "fav");
            return (Criteria) this;
        }

        public Criteria andFavBetween(Integer value1, Integer value2) {
            addCriterion("fav between", value1, value2, "fav");
            return (Criteria) this;
        }

        public Criteria andFavNotBetween(Integer value1, Integer value2) {
            addCriterion("fav not between", value1, value2, "fav");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table download_history
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table download_history
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}