package com.p1.pojo;

public class DownloadHistory {
    public static final int IS_FAV=1;
    public static final int NO_FAV=0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download_history.download_history_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private Integer downloadHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download_history.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download_history.user_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download_history.fav
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private Integer fav;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download_history.download_history_id
     *
     * @return the value of download_history.download_history_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Integer getDownloadHistoryId() {
        return downloadHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download_history.download_history_id
     *
     * @param downloadHistoryId the value for download_history.download_history_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setDownloadHistoryId(Integer downloadHistoryId) {
        this.downloadHistoryId = downloadHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download_history.rid
     *
     * @return the value of download_history.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download_history.rid
     *
     * @param rid the value for download_history.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download_history.user_id
     *
     * @return the value of download_history.user_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download_history.user_id
     *
     * @param userId the value for download_history.user_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download_history.fav
     *
     * @return the value of download_history.fav
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Integer getFav() {
        return fav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download_history.fav
     *
     * @param fav the value for download_history.fav
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setFav(Integer fav) {
        this.fav = fav;
    }

}