package com.p1.pojo;

public class SearchHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.search_history_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private Integer searchHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_history.user_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.search_history_id
     *
     * @return the value of search_history.search_history_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Integer getSearchHistoryId() {
        return searchHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.search_history_id
     *
     * @param searchHistoryId the value for search_history.search_history_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setSearchHistoryId(Integer searchHistoryId) {
        this.searchHistoryId = searchHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.rid
     *
     * @return the value of search_history.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.rid
     *
     * @param rid the value for search_history.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_history.user_id
     *
     * @return the value of search_history.user_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_history.user_id
     *
     * @param userId the value for search_history.user_id
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}