package com.p1.pojo;

public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.song_name
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private String songName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.artist
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private String artist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.album
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private String album;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.duration
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.url
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.rid
     *
     * @return the value of song.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.rid
     *
     * @param rid the value for song.rid
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.song_name
     *
     * @return the value of song.song_name
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public String getSongName() {
        return songName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.song_name
     *
     * @param songName the value for song.song_name
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setSongName(String songName) {
        this.songName = songName == null ? null : songName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.artist
     *
     * @return the value of song.artist
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public String getArtist() {
        return artist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.artist
     *
     * @param artist the value for song.artist
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setArtist(String artist) {
        this.artist = artist == null ? null : artist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.album
     *
     * @return the value of song.album
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public String getAlbum() {
        return album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.album
     *
     * @param album the value for song.album
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setAlbum(String album) {
        this.album = album == null ? null : album.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.duration
     *
     * @return the value of song.duration
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.duration
     *
     * @param duration the value for song.duration
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.url
     *
     * @return the value of song.url
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.url
     *
     * @param url the value for song.url
     *
     * @mbg.generated Tue Feb 28 17:37:46 GMT+08:00 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}